spring:
  application:
    name: micro-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: lggww
    url: jdbc:mysql://localhost:3306/domo
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090

server:
  port: 8090
logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    org.springframework.security.oauth2.server: trace
    org.springframework.security.oauth2.jwt: trace
